# Burster Izhikevich - Segregated Pipeline

In [1]:
from act.SyntheticGenerator import SyntheticGenerator
from act.act_types import SimParams, OptimizationParameters
from act.cell_model import TargetCell, ModuleParameters

random_seed = 43
num_slices = 4
experiment_folder = f"output/bursterIzh_seg_filtered_sl-{num_slices}/{random_seed}"
target_folder = experiment_folder + "/target"

# module 1 is for spiking, module 2 for bursting, final for refining all channels
module_1_folder = experiment_folder + "/module_1"
module_2_folder = experiment_folder + "/module_2"
module_final_folder = experiment_folder + "/module_final"

target_cell = TargetCell(
    hoc_file="/home/mwsrgf/proj/ACT/data/Burster_Izhikevich/seg/template.hoc",
    mod_folder="/home/mwsrgf/proj/ACT/data/Burster_Izhikevich/seg",
    cell_name="Burster_Izh",
    g_names = ["gbar_na3", "gkdrbar_kdr","gbar_nap","gmbar_im", "glbar_leak"]
)

sim_par= SimParams(
            h_v_init=-67.0,  # Consistent with nrngui settings
            h_tstop=500,     # Simulation time in ms
            h_dt=0.1,      # Time step in ms
            h_celsius=6.3,   # Temperature in degrees Celsius
            CI_type="constant",
            CI_amps=[0.1,0.2,0.3],   # Current injection amplitude
            CI_dur=300,      # Duration of current injection
            CI_delay=100,     # Delay before current injection
            set_g_to=[]
        )

/home/mwsrgf/act-venv/lib64/python3.9/site-packages/torch/__init__.py:955: UserWarning: torch.set_default_tensor_type() is deprecated as of PyTorch 2.1, please use torch.set_default_dtype() and torch.set_default_device() as alternatives. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:432.)
  _C._set_default_tensor_type(t)
--No graphics will be displayed.


# Generate Synthetic Data

In [2]:
sg = SyntheticGenerator(
    ModuleParameters(
        module_folder_name=target_folder,
        cell= target_cell,
        sim_params= sim_par,
        optim_params = OptimizationParameters(
            blocked_channels= []
        )
    )
)

sg.generate_synthetic_target_data("target_data.csv")

Blocking: []
Total number of jobs: 3
Total number of proccessors: 192
/home/mwsrgf/proj/ACT/output/bursterIzh_seg_filtered_sl-4/43/target/synthetic_0.1_0.2_0.3_


In [3]:
#import matplotlib.pyplot as plt
#import numpy as np

#data = np.load("/home/mwsrgf/proj/ACT/output/bursterIzh_seg_filtered_sl-10/42/module_1/train/combined_out.npy")

#Volt = data[:,:,0]

#plt.plot(Volt[1,:])

In [4]:
passive_sim_par = SimParams(
            h_v_init = -67,
            h_tstop = 1500,
            h_dt = 0.001,
            h_celsius = 6.3,
            CI_type = "constant",
            CI_amps = [-1],    ##################### NEGATIVE CURRENT INJECTION ###################
            CI_dur = 1000,
            CI_delay = 500,
            set_g_to=[]
        )

sg_passive = SyntheticGenerator(
    ModuleParameters(
        module_folder_name=target_folder,
        cell= target_cell,
        sim_params= passive_sim_par,
        optim_params = OptimizationParameters(
            blocked_channels= []
        )
    )
)

sg_passive.generate_synthetic_target_data("passive_data.csv")

Blocking: []
Total number of jobs: 1
Total number of proccessors: 192
MECHANISMS already loaded.
/home/mwsrgf/proj/ACT/output/bursterIzh_seg_filtered_sl-4/43/target/synthetic_-1_


# Get Passive Properties

In [5]:
from act.PassivePropertiesModule import PassivePropertiesModule
from act.act_types import SimParams
from act.cell_model import TrainCell

train_cell = TrainCell(
    hoc_file="/home/mwsrgf/proj/ACT/data/Burster_Izhikevich/seg/template.hoc",
    mod_folder="/home/mwsrgf/proj/ACT/data/Burster_Izhikevich/seg",
    cell_name="Burster_Izh",
    g_names = ["gbar_na3", "gkdrbar_kdr","gbar_nap","gmbar_im", "glbar_leak"]
)

passive_mod = PassivePropertiesModule(
    train_cell=train_cell,
    sim_params=passive_sim_par,
    trace_filepath=f"{target_folder}/passive_data.csv",
    leak_conductance_variable="glbar_leak",
    leak_reversal_variable="el_leak"
)

In [6]:
passive_mod.set_passive_properties()
print(train_cell.passive_properties)

MECHANISMS already loaded.
Found 1 section(s) in this cell. Calculating the total surface area of the cell.
PassiveProperties(V_rest=-70.07262004640518, R_in=306.36820650467416, tau=69.423, Cm=2.499821798209222, g_bar_leak=3.60085533354828e-05, cell_area=9.064641486925113e-05, leak_conductance_variable='glbar_leak', leak_reversal_variable='el_leak')


## Run Module 1 (Spiking)

In [7]:
from act.ACTModule import ACTModule
from act.act_types import OptimizationParameters, OptimizationParam
from act.cell_model import ModuleParameters

'''
OptimizationParam(param="gbar_na3", low=0.025, high=0.075, n_slices=num_slices),
OptimizationParam(param="gkdrbar_kdr", low=0.015, high=0.045, n_slices=num_slices),
OptimizationParam(param="gbar_nap", low=0.0002, high=0.0006, n_slices=num_slices),
OptimizationParam(param="gmbar_im", low=0.0019, high=0.0057, n_slices=num_slices),
OptimizationParam(param="glbar_leak", prediction=train_cell.passive_properties.g_bar_leak, bounds_variation=0.0, n_slices=1)
'''

# gmbar_im = 0.0038, gkdrbar_kdr= 0.03, gbar_nap= 0.0004, gbar_na3= 0.05, glbar_leak= 3.6e-5
mod1 = ACTModule(
    ModuleParameters(
        module_folder_name=module_1_folder,
        cell= train_cell,
        target_traces_file = f"{target_folder}/target_data.csv",
        sim_params= sim_par,
        optim_params= OptimizationParameters(
            g_ranges_slices= [
                OptimizationParam(param="gbar_na3", low=0.025, high=0.075, n_slices=num_slices),
                OptimizationParam(param="gkdrbar_kdr", low=0.015, high=0.045, n_slices=num_slices),
                OptimizationParam(param="gbar_nap", blocked=True),
                OptimizationParam(param="gmbar_im", blocked=True),
                OptimizationParam(param="glbar_leak", prediction=train_cell.passive_properties.g_bar_leak, bounds_variation=0.0, n_slices=1)
            ],
            filtered_out_features = ["no_spikes", "saturated"],
            train_features=["i_trace_stats", "number_of_spikes", "spike_times", "spike_height_stats", "number_of_troughs", "trough_times", "trough_height_stats"],
            prediction_eval_method='fi_curve',
            spike_threshold=0,
            saturation_threshold=-55,
            window_of_inspection=(120,400),
            first_n_spikes=20,
            random_state=random_seed,
            save_file=f"{module_1_folder}/results/saved_metrics.json"
        )
    )
)

In [8]:
predicted_g_data_file = mod1.run()

RUNNING THE MODULE
LOADING TARGET TRACES
SIMULATING TRAINING DATA
Total number of jobs: 48
Total number of proccessors: 192
MECHANISMS already loaded.
/home/mwsrgf/proj/ACT/output/bursterIzh_seg_filtered_sl-4/43/module_1/train
FILTERING DATA
Dropping 0 traces where: All values in the window (1200:4000) are saturated (above -55 mV).
Dropping 0 traces where: No spikes are in the voltage trace.
Dataset size after filtering: 48. Saving to /home/mwsrgf/proj/ACT/output/bursterIzh_seg_filtered_sl-4/43/module_1/train/filtered_out.npy
TRAINING RANDOM FOREST REGRESSOR
Training Random Forest on Filtered Data
Extracting features: ['I_mean', 'I_stdev', 'Num Spikes', 'Spike Time 1', 'Spike Time 2', 'Spike Time 3', 'Spike Time 4', 'Spike Time 5', 'Spike Time 6', 'Spike Time 7', 'Spike Time 8', 'Spike Time 9', 'Spike Time 10', 'Spike Time 11', 'Spike Time 12', 'Spike Time 13', 'Spike Time 14', 'Spike Time 15', 'Spike Time 16', 'Spike Time 17', 'Spike Time 18', 'Spike Time 19', 'Spike Time 20', 'Min Sp

In [9]:
mod1.pickle_rf(mod1.rf_model,f"{module_1_folder}/trained_rf.pkl")
print(train_cell.predicted_g)

{'gbar_na3': 0.03966666666666647, 'gkdrbar_kdr': 0.019720000000000154, 'gbar_nap': 0.0, 'gmbar_im': 0.0, 'glbar_leak': 3.600855333548278e-05}


In [10]:
if hasattr(train_cell, '__dict__'):
    # Print all keys and values
    for key, value in train_cell.__dict__.items():
        print(f"{key}: {value}")
else:
    print("This object does not have a __dict__ attribute.")

hoc_file: /home/mwsrgf/proj/ACT/data/Burster_Izhikevich/seg/template.hoc
mod_folder: /home/mwsrgf/proj/ACT/data/Burster_Izhikevich/seg
cell_name: Burster_Izh
passive_properties: PassiveProperties(V_rest=-70.07262004640518, R_in=306.36820650467416, tau=69.423, Cm=2.499821798209222, g_bar_leak=3.60085533354828e-05, cell_area=9.064641486925113e-05, leak_conductance_variable='glbar_leak', leak_reversal_variable='el_leak')
cell_area: None
CI: []
g_names: ['gbar_na3', 'gkdrbar_kdr', 'gbar_nap', 'gmbar_im', 'glbar_leak']
gleak_var: None
g_bar_leak: None
predicted_g: {'gbar_na3': 0.03966666666666647, 'gkdrbar_kdr': 0.019720000000000154, 'gbar_nap': 0.0, 'gmbar_im': 0.0, 'glbar_leak': 3.600855333548278e-05}


## Run Module 2 (Bursting)

In [11]:
from act.ACTModule import ACTModule
from act.act_types import OptimizationParameters, OptimizationParam
from act.cell_model import ModuleParameters

'''
OptimizationParam(param="gbar_na3", low=0.025, high=0.075, n_slices=num_slices), # Real: 0.05
OptimizationParam(param="gkdrbar_kdr", low=0.015, high=0.045, n_slices=num_slices), # Real: 0.03
OptimizationParam(param="gbar_nap", low=0.0002, high=0.0006, n_slices=num_slices),  # Real: 0.0004
OptimizationParam(param="gmbar_im", low=0.0019, high=0.0057, n_slices=num_slices),  # Real: 0.0038
OptimizationParam(param="glbar_leak", prediction=train_cell.passive_properties.g_bar_leak, bounds_variation=0.0, n_slices=1)
'''
# Allow all channels to vary by 20% their predicted value in the previous module
bounds_variation = 0.2

# gmbar_im = 0.0038, gkdrbar_kdr= 0.03, gbar_nap= 0.0004, gbar_na3= 0.05, glbar_leak= 3.6e-5
mod2 = ACTModule(
    ModuleParameters(
        module_folder_name=module_2_folder,
        cell= train_cell,
        target_traces_file = f"{target_folder}/target_data.csv",
        sim_params= sim_par,
        optim_params= OptimizationParameters(
            g_ranges_slices= [
                OptimizationParam(param="gbar_na3", prediction=train_cell.predicted_g["gbar_na3"], bounds_variation=bounds_variation, n_slices=num_slices),
                OptimizationParam(param="gkdrbar_kdr", prediction=train_cell.predicted_g["gkdrbar_kdr"], bounds_variation=bounds_variation, n_slices=num_slices),
                OptimizationParam(param="gbar_nap", low=0.0002, high=0.0006, n_slices=num_slices),
                OptimizationParam(param="gmbar_im", low=0.0019, high=0.0057, n_slices=num_slices),
                OptimizationParam(param="glbar_leak", prediction=train_cell.passive_properties.g_bar_leak, bounds_variation=0.0, n_slices=1)
            ],
            filtered_out_features = ["no_spikes", "saturated"],
            train_features=["i_trace_stats", "number_of_spikes", "spike_times", "spike_height_stats", "number_of_troughs", "trough_times", "trough_height_stats"],
            prediction_eval_method='fi_curve',
            spike_threshold=0,
            saturation_threshold=-67,
            first_n_spikes=20,
            random_state=random_seed,
            save_file=f"{module_2_folder}/results/saved_metrics.json"
        )
    )
)

In [12]:
predicted_g_data_file = mod2.run()

RUNNING THE MODULE
LOADING TARGET TRACES
SIMULATING TRAINING DATA
Total number of jobs: 768
Total number of proccessors: 192
MECHANISMS already loaded.
/home/mwsrgf/proj/ACT/output/bursterIzh_seg_filtered_sl-4/43/module_2/train
FILTERING DATA
Dropping 414 traces where: All values in the window (3100:4000) are saturated (above -67 mV).
Dropping 0 traces where: No spikes are in the voltage trace.
Dataset size after filtering: 354. Saving to /home/mwsrgf/proj/ACT/output/bursterIzh_seg_filtered_sl-4/43/module_2/train/filtered_out.npy
TRAINING RANDOM FOREST REGRESSOR
Training Random Forest on Filtered Data
Extracting features: ['I_mean', 'I_stdev', 'Num Spikes', 'Spike Time 1', 'Spike Time 2', 'Spike Time 3', 'Spike Time 4', 'Spike Time 5', 'Spike Time 6', 'Spike Time 7', 'Spike Time 8', 'Spike Time 9', 'Spike Time 10', 'Spike Time 11', 'Spike Time 12', 'Spike Time 13', 'Spike Time 14', 'Spike Time 15', 'Spike Time 16', 'Spike Time 17', 'Spike Time 18', 'Spike Time 19', 'Spike Time 20', 'Mi

In [13]:
mod2.pickle_rf(mod2.rf_model,f"{module_2_folder}/trained_rf.pkl")
print(train_cell.predicted_g)

{'gbar_na3': 0.04748364444444491, 'gkdrbar_kdr': 0.023090805333333405, 'gbar_nap': 0.00042946666666666896, 'gmbar_im': 0.003347800000000019, 'glbar_leak': 3.600855333548278e-05}


In [14]:
if hasattr(train_cell, '__dict__'):
    # Print all keys and values
    for key, value in train_cell.__dict__.items():
        print(f"{key}: {value}")
else:
    print("This object does not have a __dict__ attribute.")

hoc_file: /home/mwsrgf/proj/ACT/data/Burster_Izhikevich/seg/template.hoc
mod_folder: /home/mwsrgf/proj/ACT/data/Burster_Izhikevich/seg
cell_name: Burster_Izh
passive_properties: PassiveProperties(V_rest=-70.07262004640518, R_in=306.36820650467416, tau=69.423, Cm=2.499821798209222, g_bar_leak=3.60085533354828e-05, cell_area=9.064641486925113e-05, leak_conductance_variable='glbar_leak', leak_reversal_variable='el_leak')
cell_area: None
CI: []
g_names: ['gbar_na3', 'gkdrbar_kdr', 'gbar_nap', 'gmbar_im', 'glbar_leak']
gleak_var: None
g_bar_leak: None
predicted_g: {'gbar_na3': 0.04748364444444491, 'gkdrbar_kdr': 0.023090805333333405, 'gbar_nap': 0.00042946666666666896, 'gmbar_im': 0.003347800000000019, 'glbar_leak': 3.600855333548278e-05}


## Run Fine Tuning Module

In [15]:
from act.ACTModule import ACTModule
from act.act_types import OptimizationParameters, OptimizationParam
from act.cell_model import ModuleParameters

'''
OptimizationParam(param="gbar_na3", low=0.025, high=0.075, n_slices=num_slices),
OptimizationParam(param="gkdrbar_kdr", low=0.015, high=0.045, n_slices=num_slices),
OptimizationParam(param="gbar_nap", low=0.0002, high=0.0006, n_slices=num_slices),
OptimizationParam(param="gmbar_im", low=0.0019, high=0.0057, n_slices=num_slices),
OptimizationParam(param="glbar_leak", prediction=train_cell.passive_properties.g_bar_leak, bounds_variation=0.0, n_slices=1)
'''
bounds_variation = 0.15

final_mod = ACTModule(
    ModuleParameters(
        module_folder_name=module_final_folder,
        cell= train_cell,
        target_traces_file = f"{target_folder}/target_data.csv",
        sim_params= sim_par,
        optim_params= OptimizationParameters(
            g_ranges_slices= [
                OptimizationParam(param="gbar_na3", prediction=train_cell.predicted_g["gbar_na3"], bounds_variation=bounds_variation, n_slices=num_slices),
                OptimizationParam(param="gkdrbar_kdr", prediction=train_cell.predicted_g["gkdrbar_kdr"], bounds_variation=bounds_variation, n_slices=num_slices),
                OptimizationParam(param="gbar_nap", prediction=train_cell.predicted_g["gbar_nap"], bounds_variation=bounds_variation, n_slices=num_slices),
                OptimizationParam(param="gmbar_im", prediction=train_cell.predicted_g["gmbar_im"], bounds_variation=bounds_variation, n_slices=num_slices),
                OptimizationParam(param="glbar_leak", prediction=train_cell.passive_properties.g_bar_leak, bounds_variation=0.0, n_slices=1)
            ],
            filtered_out_features = ["no_spikes", "saturated"],
            train_features=["i_trace_stats", "number_of_spikes", "spike_times", "spike_height_stats", "number_of_troughs", "trough_times", "trough_height_stats"],
            spike_threshold=0,
            saturation_threshold=-65,
            first_n_spikes=20,
            prediction_eval_method='fi_curve',
            random_state=random_seed,
            save_file=f"{module_final_folder}/results/saved_metrics.json"
        )
    )
)

In [16]:
final_predicted_g_data_file = final_mod.run()

RUNNING THE MODULE
LOADING TARGET TRACES
SIMULATING TRAINING DATA
Total number of jobs: 768
Total number of proccessors: 192
MECHANISMS already loaded.
/home/mwsrgf/proj/ACT/output/bursterIzh_seg_filtered_sl-4/43/module_final/train
FILTERING DATA
Dropping 88 traces where: All values in the window (3100:4000) are saturated (above -65 mV).
Dropping 0 traces where: No spikes are in the voltage trace.
Dataset size after filtering: 680. Saving to /home/mwsrgf/proj/ACT/output/bursterIzh_seg_filtered_sl-4/43/module_final/train/filtered_out.npy
TRAINING RANDOM FOREST REGRESSOR
Training Random Forest on Filtered Data
Extracting features: ['I_mean', 'I_stdev', 'Num Spikes', 'Spike Time 1', 'Spike Time 2', 'Spike Time 3', 'Spike Time 4', 'Spike Time 5', 'Spike Time 6', 'Spike Time 7', 'Spike Time 8', 'Spike Time 9', 'Spike Time 10', 'Spike Time 11', 'Spike Time 12', 'Spike Time 13', 'Spike Time 14', 'Spike Time 15', 'Spike Time 16', 'Spike Time 17', 'Spike Time 18', 'Spike Time 19', 'Spike Time 2

In [17]:
final_mod.pickle_rf(final_mod.rf_model,f"{module_final_folder}/trained_rf.pkl")
print(train_cell.predicted_g)

{'gbar_na3': 0.046894847253333254, 'gkdrbar_kdr': 0.02298458762880047, 'gbar_nap': 0.00039133002666666736, 'gmbar_im': 0.0034639686600000277, 'glbar_leak': 3.600855333548278e-05}


In [18]:
if hasattr(train_cell, '__dict__'):
    # Print all keys and values
    for key, value in train_cell.__dict__.items():
        print(f"{key}: {value}")
else:
    print("This object does not have a __dict__ attribute.")

hoc_file: /home/mwsrgf/proj/ACT/data/Burster_Izhikevich/seg/template.hoc
mod_folder: /home/mwsrgf/proj/ACT/data/Burster_Izhikevich/seg
cell_name: Burster_Izh
passive_properties: PassiveProperties(V_rest=-70.07262004640518, R_in=306.36820650467416, tau=69.423, Cm=2.499821798209222, g_bar_leak=3.60085533354828e-05, cell_area=9.064641486925113e-05, leak_conductance_variable='glbar_leak', leak_reversal_variable='el_leak')
cell_area: None
CI: []
g_names: ['gbar_na3', 'gkdrbar_kdr', 'gbar_nap', 'gmbar_im', 'glbar_leak']
gleak_var: None
g_bar_leak: None
predicted_g: {'gbar_na3': 0.046894847253333254, 'gkdrbar_kdr': 0.02298458762880047, 'gbar_nap': 0.00039133002666666736, 'gmbar_im': 0.0034639686600000277, 'glbar_leak': 3.600855333548278e-05}


# Results & Metrics

In [19]:
from act import ACTPlot
ACTPlot.plot_v_comparison(
    final_predicted_g_data_file, 
    module_final_folder, 
    sim_par["CI_amps"],
    sim_par["h_dt"]
    )

ACTPlot.plot_fi_comparison(
    module_final_folder, 
    sim_par["CI_amps"]
    )

In [20]:
from act.Metrics import Metrics

metrics = Metrics()

mean, stdev = metrics.print_interspike_interval_comparison(
    module_final_folder,
    final_predicted_g_data_file,
    sim_par["CI_amps"], 
    sim_par["h_dt"],
    first_n_spikes=5,
    save_file=f"{module_final_folder}/results/saved_metrics.json"
)

metrics.print_prediction_g_mae(
    actual_g={"gbar_na3": 0.05, "gkdrbar_kdr": 0.03,"gbar_nap": 0.0004,"gmbar_im": 0.0038, "glbar_leak": 3.6e-5},
    save_file=f"{module_final_folder}/results/saved_metrics.json"
)

Interspike times (Target): [[2.610e+01 2.180e+02 1.000e+06 1.000e+06]
 [2.200e+01 3.780e+01 1.976e+02 1.000e+06]
 [1.970e+01 2.320e+01 1.000e+06 1.000e+06]]
Interspike times (Prediction): [[2.450e+01 2.219e+02 1.000e+06 1.000e+06]
 [2.110e+01 3.040e+01 1.945e+02 1.000e+06]
 [1.910e+01 2.210e+01 1.000e+06 1.000e+06]]
MAE for each I injection: [1.3749999999999858, 2.8499999999999908, 0.4249999999999936]
Mean interspike-interval MAE: 1.54999999999999
Standard Deviation interspike-interval MAE: 0.9977057014303693
MAE of final g prediction: 0.002093054996907013
